doctrine:
    dbal:
        driver: pdo_mysql
        server_version: '8.0'

        dbname: '%env(string:DATABASE_NAME)%'
        host: '%env(string:DATABASE_HOST)%'
        port: '%env(int:DATABASE_PORT)%'
        user: '%env(string:DATABASE_USER)%'
        password: '%env(string:DATABASE_PASSWORD)%'

        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
