version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/var/www/project:cached
    env_file:
      - .env
    environment:
      - PORT=${APP_HTTP_PORT:-80}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    ports:
      - "${APP_HTTP_PORT:-80}:${APP_HTTP_PORT:-80}"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8089:3306"

  node:
    image: node:12-alpine
    command: sh -c "yarn install && yarn encore dev --watch"
    volumes:
      - .:/app:cached
    working_dir: /app

  composer:
    image: composer:latest
    command: install
    volumes:
      - .:/app
